Revert "Bump Compose navigation version"
This reverts commit 0051997e17ec37b07481b2762a1969524bce355d.

The new version was causing java.lang.NoSuchMethodError: No static method HorizontalPager...